version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/circleci # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/ruby:2.5.1-stretch

    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
      - run: sudo apt-get install -y liblapack-dev npm nodejs
      - run: ./bin/setup
      - run: ./bin/production
      - run: bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension --check-opengraph --url-ignore "feed.xml"
